### ISSUE TITLE
Packaging and distributing on the Linux app store, Flathub.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#78]
Packaging and distributing on the Linux app store, Flathub.

Hi,

I want to package LG4X as a Flatpak and distribute it on Flathub for the Linux operating system. I know how to do it.
Currently, LG4X is missing a logo. I know how to use Inkscape, so if you have a logo you want, I can draw it.

The advantage of using Flatpak is that Python modules can be packaged into the app and used without installing extra modules. A desktop icon will be created when it is installed. Update for the user along with other apps when we push a new update. Flatpak is distro-agnostic, which means it can be installed on any distro.

https://flathub.org/

Let me know what you think.

**Comment by Julian-Hochhaus** [comment]
Great idea! 
Are there constraints regarding the logo? I assume the logo should be in square format and should be looking nice even in low resolution?!

Some questions regarding flatpak:

How does flatpak handle licenses? 
What happens if dependencies are changed?
Does the flatpak app automatically update with each release? Or is it triggered by pushes to specific branches?
Do I need something like an account to publish on flathub? Is it possible to set up something like an organisation as publisher? Because I would like to have write access/ admin access to all flathub stuff too (but especially if you know how to do it, feel free to set everything up, I only want to be sure that I have access just in case).

**Comment by Julian-Hochhaus** [comment]
BTW: Feel free to create logo suggestions. I would like to include something like fitted spectra and the name LG4X (and maybe a 2 for version 2) in the logo. Another suggestion from my side would be something like a fitted peak with two or three components and the word 'Fit' or 'XPS-Fit'

**Comment by kevinsmia1939** [comment]
The license of the program itself is specified in the metadata.info.xml file under project_license, which will be displayed on the Flathub store front, for example, https://github.com/kevinsmia1939/PySimpleCV/blob/main/data/io.github.kevinsmia1939.PySimpleCV.metainfo.xml

The dependencies can be changed or added by editing the manifest file. For example, to add numpy,

```
  - name: python-numpy
    buildsystem: simple
    build-commands:
      - python3 -mpip install . --no-index --find-links=file://${PWD} --prefix=${FLATPAK_DEST}
        --no-build-isolation
    sources:
      - type: archive
        url: https://files.pythonhosted.org/packages/2c/d4/590ae7df5044465cc9fa2db152ae12468694d62d952b1528ecff328ef7fc/numpy-1.24.3.tar.gz
        sha256: ab344f1bf21f140adab8e47fdbc7c35a477dc01408791f8ba00d018dd0bc5155
        x-checker-data:
          type: pypi
          name: numpy
```
It can automatically check for updates using the field under x-checker-data. Git is also supported.
```
        x-checker-data:
          type: git
          tag-pattern: ^(release-[\d.]+)$
```
Once the update is found, a Flathub bot automatically adds a pull request, for example,
https://github.com/flathub/io.github.kevinsmia1939.PySimpleCV/pull/25

Only a Github account is needed since all the requests to add new apps are here: https://github.com/flathub/flathub/pulls
Then someone will invite you as a maintainer; just comment under the PR.
